[package]
name = "ABtree"
<<<<<<< HEAD
version = "0.2.0"
=======
version = "0.4.0"
>>>>>>> 84954ae9b1239a3c9888a03a3b3800352bb8eb12
edition = "2018"
author = ["Dfree"]
description = "AVL and Btree for rust"
license = "MIT"
include = [
	"src/**/*",
	"Cargo.toml",
	"README.md"
]
repository = "https://github.com/GuoHao150/ABtree"
keywords = [
	"AVL",
	"Btree"
]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[profile.release]
opt-level = 3

[dependencies]
